language: "python"
python:
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage

script: nosetests #--with-coverage

after_success:
  coveralls
